[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.14",
    "fastapi>=0.116.1",
    "mcp[cli]>=1.12.0",
    "oracledb>=3.2.0",
    "uvicorn>=0.35.0",
]
